import type { Config } from '@react-router/dev/config';

export default {
  // The design spec lays the app out as src/components, src/routes, src/styles
  // rather than React Router's default `app/`. See
  // docs/superpowers/specs/2026-08-07-react-migration-design.md section 5.
  appDirectory: 'src',

  // NOT the default `build/`. The repository root already contains build/ —
  // the Python static site generator — and this app is nested one level down,
  // so a default-named output directory invites confusion between the two
  // during the stages where both exist.
  buildDirectory: 'dist',

  // Prerendered SPA: loaders run at build time and every listed URL is written
  // as a complete HTML document, then hydrates client-side. This is the
  // mechanism that keeps 392 indexed URLs crawlable without a server.
  ssr: false,

  // S4 prerender list.
  // Group 1 (Home): 1 route
  // Group 2 (Core): 7 routes
  // Group 3 (Academics): 14 routes
  // Group 4 (People): 64 routes
  // Group 5 (Research): 89 routes (1 main + 1 facilities + 4 categories + 83 details)
  prerender: [
    '/',
    '/about',
    '/contact',
    '/campus',
    '/admissions',
    '/search',
    '/accessibility',
    '/sitemap',
    '/academics',
    '/academics/btech',
    '/academics/mtech',
    '/academics/phd',
    '/academics/programs',
    '/academics/programs/mtech-cse',
    '/academics/programs/mtech-nanotechnology',
    '/academics/programs/mtech-energy-science-technology',
    '/academics/programs/mtech-mechatronics',
    '/academics/programs/mtech-manufacturing-technology-automation',
    '/academics/programs/phd-cse',
    '/academics/programs/phd-mechatronics',
    '/academics/programs/phd-nanotechnology',
    '/academics/programs/btech',
    '/people',
    '/people/faculty',
    '/people/faculty/anuj-kumar-sharma',
    '/people/faculty/saurabh-mishra',
    '/people/faculty/av-ullas',
    '/people/faculty/siddharth-yadav',
    '/people/faculty/vijay-singh',
    '/people/faculty/vibhu-kumar-tripathi',
    '/people/faculty/naresh-chandra-maurya',
    '/people/faculty/parul-singh',
    '/people/faculty/prachi-gupta',
    '/people/faculty/narendra-pal',
    '/people/faculty/hrishikesh-kumar-singh',
    '/people/faculty/chandramani-upadhyay',
    '/people/faculty/rohit-prakash',
    '/people/former',
    '/people/former/mk-dutta',
    '/people/former/manish-gaur',
    '/people/former/piyush-jaiswal',
    '/people/former/shiv-prakash',
    '/people/former/arun-kumar',
    '/people/former/rabesh-kumar-singh',
    '/people/former/jitendra-kumar',
    '/people/former/gopal-ji',
    '/people/former/pushpendra-kumar-singh-rathore',
    '/people/former/gyanprakash-d-maurya',
    '/people/former/dipesh-kumar-mishra',
    '/people/former/pappu-kumar-harijan',
    '/people/former/prateek-raj-gautam',
    '/people/former/jagrati-singh',
    '/people/former/manjari-shukla',
    '/people/former/ashu-sharma',
    '/people/former/sajal-agarwal',
    '/people/former/anupam-keshari',
    '/people/former/brajendra-singh-sengar',
    '/people/former/narendra-singh',
    '/people/former/dipesh-kumar',
    '/people/former/ramkrishna-sahoo',
    '/people/former/neelam-dayal',
    '/people/former/manish-raj',
    '/people/former/amrit-pal',
    '/people/former/chitra-singh',
    '/people/former/prashant-rawat',
    '/people/former/vrinda-yadav',
    '/people/former/anamika-jain',
    '/people/former/biswajit-mandal',
    '/people/former/varun-chitransh',
    '/people/former/chandresh-kumar-rastogi',
    '/people/visiting',
    '/people/visiting/kb-naik',
    '/people/visiting/vijay-tiwari',
    '/people/visiting/kv-arya',
    '/people/visiting/vrijendra-singh',
    '/people/visiting/manish-kumar',
    '/people/staff',
    '/people/staff/veer-vikram-singh',
    '/people/staff/diyanshu-chauhan',
    '/people/staff/gaurav-rai',
    '/people/staff/shubhi-pandey',
    '/people/staff/sadka-kouser',
    '/people/staff/ram-kumar-pathak',
    '/people/staff/anurag-chaubey',
    '/people/staff/monika-singh',
    '/people/staff/mukesh-kumar-mourya',
    '/research',
    '/research/facilities',
    '/research/publications',
    '/research/publications/automated-detection-of-bioimages-using-novel-deep-feature-fusion-algorithm-and-a',
    '/research/publications/alsd-net-automatic-lung-sounds-diagnosis-network-from-pulmonary-signals',
    '/research/publications/ensemble-based-machine-learning-approach-for-prediction-of-glioma-and-multi-grad',
    '/research/publications/a-low-cost-imaging-framework-for-freshness-evaluation-from-multifocal-fish-tissu',
    '/research/publications/an-efficient-deep-neural-network-based-abnormality-detection-and-multi-class-bre',
    '/research/publications/fast-charging-high-energy-battery-supercapacitor-hybrid-anodic-reduced-graphene-',
    '/research/publications/a-robust-zero-watermarking-scheme-for-tele-ophthalmological-applications',
    '/research/publications/lemon-seeds-as-green-coating-material-for-mitigation-of-mild-steel-corrosion-in-',
    '/research/publications/deep-learning-neural-networks-for-acrylamide-identification-in-potato-chips-usin',
    '/research/publications/halloysite-nanotubes-reinforced-epoxy-glass-microballoons-syntactic-foams',
    '/research/publications/novel-application-of-graphite-talc-hybrid-nanoparticle-enriched-cutting-fluid-in',
    '/research/publications/automatic-diagnosis-of-multiple-cardiac-diseases-from-pcg-signals-using-convolut',
    '/research/publications/machine-learning-based-classification-of-cardiac-diseases-from-pcg-recorded-hear',
    '/research/publications/automatic-computer-vision-based-detection-and-quantitative-analysis-of-indicativ',
    '/research/publications/writer-identification-approach-by-holistic-graphometric-features-using-offline-h',
    '/research/publications/improving-the-performance-of-the-lip-identification-through-the-use-of-shape-cor',
    '/research/patents',
    '/research/patents/a-system-and-method-for-machine-learning-based-automatic-detection-of-abnormalit',
    '/research/patents/multi-mode-real-time-object-detector-and-obstacle-aware-assistive-system-for-vis',
    '/research/patents/artificial-intelligence-based-system-and-method-for-multi-class-classification-o',
    '/research/patents/automatic-detection-of-lungs-disease-using-machine-learning-from-respiratory-sou',
    '/research/patents/artificial-intelligence-based-covid-19-screening-tool-based-on-analysis-of-x-ray',
    '/research/patents/system-and-method-for-sanitizing-currency-note-s',
    '/research/patents/the-rapid-multipurpose-disinfector',
    '/research/patents/oxygen-monitoring-control-multi-functional-convertible-robot-for-hospitals',
    '/research/patents/itpi-steel-and-mining-waste-management-intelligent-technology-and-process-manage',
    '/research/patents/oil-remediation-composite-and-method-for-synthesis-thereof',
    '/research/equipment',
    '/research/equipment/nvidia-dgx-2-server-two-petaflops-system',
    '/research/equipment/bet-measurement-system',
    '/research/equipment/industrial-robotic-center',
    '/research/equipment/industrial-automation-lab',
    '/research/equipment/3d-printing-lab',
    '/research/equipment/design-and-simulation-center',
    '/research/equipment/sensor-drives-control-lab',
    '/research/equipment/pin-on-disc-tribometer',
    '/research/equipment/human-non-invasive-blood-pressure-nibp-monitor',
    '/research/equipment/equi-vital-physiological-monitoring-system',
    '/research/equipment/markerless-motion-capture-system-2-d-gait-analysis-with-force-plate',
    '/research/equipment/emotiv-epoc-14-channel-mobile-eeg',
    '/research/equipment/auditory-brainstem-response-abr-audiometry-system',
    '/research/equipment/delsys-wireless-emg-system',
    '/research/equipment/flir-e5-thermal-imaging-camera',
    '/research/equipment/sensenuts',
    '/research/equipment/material-chemistry-synthesis-laboratory',
    '/research/equipment/field-emission-scanning-electron-microscope-fe-sem-with-edax-module',
    '/research/equipment/electrochemical-workstation',
    '/research/equipment/impedance-analyser',
    '/research/equipment/voyager-cyber-city-simulator',
    '/research/equipment/solar-simulator',
    '/research/equipment/hp-z238-microtower-workstations-google-developers-code-lab',
    '/research/equipment/augmented-reality-lab',
    '/research/equipment/microwave-reactor-anton-paar-monowave-450',
    '/research/equipment/drop-shape-analyzer-dsa100',
    '/research/equipment/automatic-micro-hardness-testing-system',
    '/research/equipment/atomic-force-microscopy-nx10',
    '/research/equipment/ftir-spectrophotometer-alpha-ii',
    '/research/equipment/uv-vis-spectrophotometer-3092',
    '/research/equipment/drone-systems-lab',
    '/research/equipment/thermogravimetric-analyser-tga',
    '/research/equipment/spray-pyrolysis-unit',
    '/research/equipment/nano-fiber-electrospinning',
    '/research/equipment/four-probe-workstation',
    '/research/equipment/dip-coating-unit',
    '/research/equipment/spin-coater',
    '/research/equipment/lee-s-disc-thermal-conductivity-apparatus',
    '/research/equipment/hall-effect-measurement',
    '/research/equipment/stereo-zoom-microscope',
    '/research/equipment/quantum-efficiency-system',
    '/research/equipment/micro-edm-machine',
    '/research/equipment/optical-microscope',
    '/research/equipment/die-electric-discharge-machining-with-mql-system',
    '/research/equipment/plc-scada-part-a',
    '/research/equipment/language-lab-with-headphones-and-i7-systems',
    '/research/equipment/linux-open-source-lab',
    '/research/equipment/general-purpose-computing-lab',
    '/research/projects',
    '/research/projects/design-and-development-of-artificial-intelligence-based-screening-tool-for-autom',
    '/research/projects/intelligent-stethoscope-a-low-cost-device-based-on-body-auscultation-for-early-m',
    '/research/projects/assistive-device-to-impart-perceptual-ability-to-visually-impaired-using-intelli',
    '/research/projects/development-of-thermal-sensors-for-measuring-the-tool-tip-temperature-and-its-on',
    '/research/projects/design-and-fabrication-of-human-hand-inspired-soft-robotic-hand-for-differently-',
    '/research/projects/computational-fluid-dynamics-cfd-analysis-for-designing-ore-transportation-throu',
    '/research/projects/development-of-novel-method-for-synthesizing-metal-oxide-carbon-nanocomposites-f',
    '/research/projects/near-net-shape-generation-of-nano-composite-parts-via-stir-casting-and-3d-printi',
    '/research/projects/development-of-sustainable-hybrid-nano-lubricant-with-improved-tribological-prop',
  ],
} satisfies Config;
