/**
 * Type definitions for institutional data collections.
 *
 * These types are derived from the JSON exports generated by
 * build/export_json.py, which pulls from build/data/*.py — the migrated
 * source of truth for institutional content. The Python modules are the
 * authority; these types describe what the export emits, not the other way
 * around.
 *
 * DO NOT hand-edit records or introduce type-only fields here. If a
 * collection's shape needs to change, change it in build/data/*.py and
 * re-export. That keeps both builds reading the same records and prevents
 * the React app from drifting into a schema the Python generator cannot
 * satisfy.
 */

/**
 * Academic programme (M.Tech / B.Tech).
 *
 * Source: build/data/programs.py
 * Count: 9
 */
export type Program = {
  slug: string;
  level: string;
  title: string;
  department: string;
  seats: string;
  approval: string;
  specializations: string[];
  vision: string;
  mission: string[];
  labs: string[];
  coordinators: string[];
  eligibility: string;
  stipend_note: string;
  source_url: string;
};

/**
 * Person record — faculty, former faculty, staff, or visiting faculty.
 *
 * All four collections (CURRENT_FACULTY, PAST_FACULTY, STAFF,
 * VISITING_FACULTY) share this shape. `department` may be null for staff and
 * some former faculty.
 *
 * Sources:
 *   build/data/people.py (current, staff, visiting)
 *   build/data/past_faculty.py (former)
 * Counts: 13 current + 32 former + 9 staff + 5 visiting = 59
 */
export type Person = {
  slug: string;
  name: string;
  title: string;
  department: string | null;
  degrees: string[];
  interests: string[];
  bio: string;
  source_url: string;
};

/**
 * Notice (admission, event, general announcement).
 *
 * Source: build/data/notices.py
 * Count: 6
 */
export type Notice = {
  slug: string;
  title: string;
  notice_type: string;
  audience: string;
  session: string;
  status: 'Open' | 'Closing soon' | 'Archived' | 'Draft' | 'Cancelled';
  summary: string;
  /** References a slug in the documents collection. */
  document_slug: string;
};

/**
 * Event (workshop, seminar, conference).
 *
 * Source: build/data/events.py
 * Count: 42
 *
 * NOTE: `id` is auto-generated by export_json.py from the title (no slug in
 * the Python source), so it may contain a numeric suffix where two events
 * share a title.
 */
export type Event = {
  id: string;
  title: string;
  mode: string;
  organizer: string;
  dates: string;
  status: string;
};

/**
 * Publication (journal article, conference paper).
 *
 * Source: build/data/publications.py
 * Count: 16
 */
export type Publication = {
  id: string;
  authors: string;
  title: string;
  venue: string;
  volume: string;
  year: string;
  doi: string;
  publisher: string;
  impact_factor: string;
};

/**
 * Patent (filed or granted).
 *
 * Source: build/data/patents.py
 * Count: 10
 */
export type Patent = {
  id: string;
  title: string;
  application_number: string;
  date: string;
  status: string;
  inventors: string;
};

/**
 * Equipment / facility.
 *
 * Source: build/data/equipment.py
 * Count: 48
 */
export type Equipment = {
  id: string;
  name: string;
  summary: string;
};

/**
 * Research project (ongoing or completed).
 *
 * Source: build/data/projects.py
 * Count: 9
 */
export type Project = {
  id: string;
  title: string;
  sponsor: string;
  investigators: string;
  amount: string;
  duration: string;
  status: string;
};

/**
 * Document (PDF syllabus, timetable, regulation, notice).
 *
 * Derived at build time from research/*.csv rather than stored, so this is
 * exported through pages/documents_pages.py. The Python build indexes these
 * into a faceted search; the React app will do the same at S5.
 *
 * Source: pages/documents_pages.load_records()
 * Count: 158
 */
export type Document = {
  slug: string;
  title: string;
  type: string;
  area: string;
  year: string;
  session: string | null;
  sizeBytes: number;
  sourceUrl: string;
  sourcePage: string;
  filename: string;
};
